### ISSUE TITLE
How to view logs? 

### ISSUE THREAD

**Issue by jeantristan** [kuzzleio/kuzzle-plugin-advanced-boilerplate#1]
## Expected Behavior

I follow the README.md. I successfully set up the boilerplate using docker.
Now I would like to debug my application.

## Current Behavior
I use `docker exec -it 231e24b82061 /bin/bash` to connect to my container. I can't manage to find a log directory. Maybe I miss something.

## Context (Environment)

Macosx. Latest stable version of Kuzzle. Using https://github.com/kuzzleio/kuzzle-vuejs-coreui-boilerplate to set up.

**Comment by Aschen** [comment]
Hello @jeantristan,

Kuzzle use a dedicated plugin to dislay/save application logs: https://github.com/kuzzleio/kuzzle-plugin-logger

This plugin is already present by default into Kuzzle and the default strategy is to display the logs to `stdout`.  
If you want to display your application logs, you can use the following command: `docker-compose -f backend/docker/docker-compose.yml logs kuzzle -f`

**Comment by jeantristan** [comment]
Thanks! That's perfect.
The command is `docker-compose -f docker/docker-compose.yml logs kuzzle`(without the last -f).
Can I do a Pull request to change the modification ?

**Comment by Aschen** [comment]
I didn't understand for what you want to do a pull request ?

**Comment by jeantristan** [comment]
To update the documentation you provide on the repository.

**Comment by Aschen** [comment]
Yes you can! Any contribution is very much appreciated
