### ISSUE TITLE
How to customize CORS allowed headers?

### ISSUE THREAD

**Issue by jeantristan** [kuzzleio/kuzzle-plugin-advanced-boilerplate#2]
I used the boilerplate. I managed to add a new plugin to exposed a new API endpoint.
This API endpoint needs a Authentication token.

When using POSTMAN, all is OK. The endpoint answers with a 200 HTTP code.
But when trying to access this endpoint within my Vue.client with the help of AXIOS i'm getting a 400 Badrequest. 

## Expected Behavior
For debuggin purpose is it possible to disabled CORS headers?

## Current Behavior
I don't know where to customize CORS headers.

**Comment by Aschen** [comment]
Hi @jeantristan,

You can configure the CORS in [Kuzzle configuration file](https://docs.kuzzle.io/guide/1/essentials/configuration/) in the [http section](https://github.com/kuzzleio/kuzzle/blob/master/.kuzzlerc.sample#L10).

But I'm not sure to understand what you want to do, if you want to restrict a custom API endpoint, it's better to use Kuzzle integrated [auth](https://docs.kuzzle.io/guide/1/essentials/user-authentication/) and [permission](https://docs.kuzzle.io/guide/1/essentials/security/) systems.

**Comment by jeantristan** [comment]
Thanks for your reply. you're right I'll switch to stackoverflow.
